version: '3.8'

services:
  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--save", "300", "1"]
  
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    command: "mosquitto -c /mosquitto-no-auth.conf"
    environment:
      - TZ=America/Los_Angeles
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on: 
      - mqtt
    devices:
      # NOTE: the following is for a laptop as it gets mounted at /dev/ttyACM0 
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_36fe43b79263ec11956c51ebee680de7-if00-port0:/dev/ttyACM0
      # NOTE: for raspberrypi 4 it gets mounted here 
      # - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=America/Los_Angeles
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mqtt:1883
    image: koenkk/zigbee2mqtt
    ports:
      # view zigbee2mqtt interface on http://localhost:3001 to add devices
      - 3001:8080
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro

  zigme-api:
    container_name: zigme-api
    build:
      context: ./zigme-api
    depends_on: 
      - redis
    environment:
      - ZIGME_REDIS_URI=redis://redis/
      - ZIGME_PUSHOVER_URI=https://api.pushover.net/1/messages.json
    # ports:
    #   # localhost:3020 will be running API
    #   - 3020:3020

    restart: unless-stopped
 
  zigme-ui:
    container_name: zigme-ui
    build:
      context: ./zigme-ui
    depends_on: 
      - zigme-api 
    ports:
      # localhost:3000 will be running zigme UI
      - 3000:3000
    env_file: 
      - .env
    restart: unless-stopped

  zigme-eventhandler:
    container_name: zigme-eventhandler
    build:
      context: ./zigme-eventhandler
    depends_on: 
      - zigbee2mqtt
      - zigme-api
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=zigbee2mqtt/+
      - ZIGME_API_HOST=zigme-api
      - ZIGME_API_PORT=3020
    # env_file: 
    #   - .env
    restart: unless-stopped
